### ISSUE TITLE
Add provisioning ISO target

### ISSUE THREAD

**Issue by bjoto** [system-transparency/system-transparency#161]
Add a new ISO target to the task infrastructure. Instead of launching Linuxboot/uroot/stboot, the iso launches launching Linuxboot/uroot/`stmgr provision hostconfig [DEFAULTS...] -efi`

The defaults should be able to be customized.

Being able to be launched from qemu would be nice as well. So, that it's easy to:
1. Build both stbootiso and proviso
2. Run proviso, which populates the efivars.
3. Run stboot, with command-line arguments that reads and launches using the efivars.

**Comment by sylv-io** [comment]
The task `proviso` was added in #160.

You can test it by running it in QEMU:
```
task proviso qemu:proviso
```

right now, it just runs the following elvish init script:
```
mount -t efivarfs none /sys/firmware/efi/efivars
stmgr provision hostconfig {{.ST_PROVISO_STMGR_ARGS}}
shutdown
```

We should probably move to `gosh`, since I was not able to script elvish in u-root (e.g. no if condition) and the elvish syntax i kinda a pain.

I'll keep this issue open for any enhancement proposals and/or UX issues.

**Comment by sylv-io** [comment]
In addition, how about adding some debug tools? We could use u-root commands or add busybox binary and a proper way to fall back to an interactive shell. Any thoughts?

**Comment by sylv-io** [comment]
#160
