### ISSUE TITLE
REGRESSION: Cannot pin stboot from config file

### ISSUE THREAD

**Issue by bjoto** [system-transparency/system-transparency#164]
Mullvad is relying on `ST_STBOOT_VERSION` to pin the git SHA for stboot. This does not longer work in 2a752fc7633e ("contrib: Adapt example host configuration").

**Comment by sylv-io** [comment]
Due to the API change and the strict parsing of JSON config files, it is hard to keep backwards compatibility. We assumed it would be better to pin all external repositories to prevent any issues due to a version mismatch. Sorry to not probably communicating this issue.

I propose that we add an optional st config variable to change the version of all pinned repositories.
In this way the user can have more control and if there are any compatibility issues, you can adapt the version of the other repos too :+1:

**Comment by bjoto** [comment]
Thanks, @sylv-io . I'm closing this one.
