### ISSUE TITLE
rename `make sign` to `make example-os-package`

### ISSUE THREAD

**Issue by jensdrenhaus** [system-transparency/system-transparency#87]
Usually an operator will use `stamanger` directly to create and sign an OS package. To provide a demo and a quick way to get started we have a make target which does this. So I guess something with a hint to example would fit better.

**Comment by sylv-io** [comment]
sounds good, However there is still the issue with the naming of each os-package.
could we remove the usage of the current date and give each os-package ist own name ?
e.g.
instead of os-pkg-<date>.zip (os-pkg-2021-03-29-10-53-07.zip)

- `ubuntu-bionic-amd64-os-pkg.zip`
- `ubuntu-focal-amd64-os-pkg.zip`
- `debian-buster-amd64-os-pkg.zip`

**Comment by sylv-io** [comment]
> sounds good, However there is still the issue with the naming of each os-package.
> could we remove the usage of the current date and give each os-package ist own name ?
> e.g.
> instead of os-pkg-.zip (os-pkg-2021-03-29-10-53-07.zip)
> 
>     * `ubuntu-bionic-amd64-os-pkg.zip`
> 
>     * `ubuntu-focal-amd64-os-pkg.zip`
> 
>     * `debian-buster-amd64-os-pkg.zip`

nevermind. it's kinda unrelated.

**Comment by sylv-io** [comment]
PR #90 merged +1
